on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 11 * * *'

name: report_gen

jobs:
  report_gen:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("tidyverse", "fs", "rmarkdown", "slider", "patchwork"))'
      - name: Generate Report
        run: |
          rmarkdown::render('sf_status.Rmd', output_file = "index.html", output_dir = "docs/")
        shell: Rscript {0}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Auto-gen Report"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
