on:
  push:
    branches:
      - master

name: report_gen

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("tidyverse", "fs", "withr", "rmarkdown", "slider", "patchwork"))'
      - name: Generate Report
        run: |
          rmarkdown::render('sf_status.Rmd', output_file = "index.html", output_dir = "docs/")
        shell: Rscript {0}
